### PR TITLE
Change behavior when handling an OFPBAC_BAD_OUT_PORT error message

### PR DESCRIPTION
**Pull request by gleybersonandrade**
Today, when an error message occurs, only an log.error is displayed. This PR increases this behavior, when the error message is OFPBAC_BAD_OUT_PORT, the interface config is checked with OFPPC_NO_FWD flag.

Fix https://github.com/kytos/of_core/issues/80

### CODE REVIEW

**Comment by ajoaoff** [comment]
In fact, besides printing the log message, an event is generated with the message. So, the better way to handle an specific error is to listen to error messages and then filter the one(s) you're insterested. Take a look at https://github.com/kytos/flow_manager/blob/05dde906be6ca7d2613a38c1962166f57bf89469/main.py#L159

**Review by ajoaoff — CHANGES_REQUESTED** [review]
In fact, besides printing the log message, an event is generated with the message. So, the better way to handle an specific error is to listen to error messages and then filter the one(s) you're insterested. Take a look at https://github.com/kytos/flow_manager/blob/05dde906be6ca7d2613a38c1962166f57bf89469/main.py#L159-L175

**Comment by gleybersonandrade** [comment]
Thanks @ajoaoff, I changed this logic to a new PR on Flow Manager (https://github.com/kytos/flow_manager/pull/88).

**Review by josemauro — CHANGES_REQUESTED** [review]
So, after the @ajoaoff suggestion, this PR is not necessary anymore?

**Comment by gleybersonandrade** [comment]
@josemauro, this PR can be closed now, all the logic present here has been moved to https://github.com/kytos/flow_manager/pull/88

**Pull request closed without merging**
